In [1]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

In [2]:
dt = pd.read_csv("data.csv")

In [3]:
dt.head(10)

I1      I3      I5      I7      I9     I11     I13     I15     I17  \
0  0.1148  0.0808  0.0382  0.0260  0.0165  0.0000  0.0009  0.0000  0.0000   
1  0.1158  0.0801  0.0382  0.0273  0.0158  0.0005  0.0001  0.0000  0.0000   
2  0.1133  0.0788  0.0383  0.0256  0.0166  0.0000  0.0004  0.0003  0.0000   
3  0.1118  0.0787  0.0370  0.0258  0.0162  0.0008  0.0000  0.0004  0.0000   
4  0.1132  0.0786  0.0388  0.0254  0.0174  0.0017  0.0011  0.0000  0.0000   
5  0.1120  0.0786  0.0385  0.0246  0.0184  0.0011  0.0000  0.0009  0.0005   
6  0.1121  0.0783  0.0373  0.0253  0.0171  0.0002  0.0010  0.0027  0.0000   
7  0.1118  0.0790  0.0387  0.0257  0.0177  0.0003  0.0000  0.0002  0.0000   
8  0.1117  0.0783  0.0384  0.0259  0.0181  0.0016  0.0005  0.0003  0.0000   
9  0.1112  0.0795  0.0381  0.0270  0.0178  0.0004  0.0008  0.0017  0.0000   

      I19  I21  I23  I25  I27  I29  Target  
0  0.0000  0.0  0.0  0.0  0.0  0.0       1  
1  0.0000  0.0  0.0  0.0  0.0  0.0       1  
2  0.0000  0.0  0.0  0.0  0.0  0.0       1  
3  0.0005  0.0  0.0  0.0  0.0  0.0       1  
4  0.0014  0.0  0.0  0.0  0.0  0.0       1  
5  0.0004  0.0  0.0  0.0  0.0  0.0       1  
6  0.0003  0.0  0.0  0.0  0.0  0.0       1  
7  0.0000  0.0  0.0  0.0  0.0  0.0       1  
8  0.0009  0.0  0.0  0.0  0.0  0.0       1  
9  0.0021  0.0  0.0  0.0  0.0  0.0       1

In [4]:
X = dt.iloc[:, 0:9]
y = dt.iloc[:, 15]

In [5]:
X.head(10)

I1      I3      I5      I7      I9     I11     I13     I15     I17
0  0.1148  0.0808  0.0382  0.0260  0.0165  0.0000  0.0009  0.0000  0.0000
1  0.1158  0.0801  0.0382  0.0273  0.0158  0.0005  0.0001  0.0000  0.0000
2  0.1133  0.0788  0.0383  0.0256  0.0166  0.0000  0.0004  0.0003  0.0000
3  0.1118  0.0787  0.0370  0.0258  0.0162  0.0008  0.0000  0.0004  0.0000
4  0.1132  0.0786  0.0388  0.0254  0.0174  0.0017  0.0011  0.0000  0.0000
5  0.1120  0.0786  0.0385  0.0246  0.0184  0.0011  0.0000  0.0009  0.0005
6  0.1121  0.0783  0.0373  0.0253  0.0171  0.0002  0.0010  0.0027  0.0000
7  0.1118  0.0790  0.0387  0.0257  0.0177  0.0003  0.0000  0.0002  0.0000
8  0.1117  0.0783  0.0384  0.0259  0.0181  0.0016  0.0005  0.0003  0.0000
9  0.1112  0.0795  0.0381  0.0270  0.0178  0.0004  0.0008  0.0017  0.0000

In [6]:
y.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
      dtype=int64)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [8]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
mlp = MLPClassifier(activation = "identity", hidden_layer_sizes=(10, 10, 10), max_iter=100)

In [10]:
mlp.fit(X_train, y_train)

c:\users\irfan\appdata\local\programs\python\python36\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:585: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='identity', hidden_layer_sizes=(10, 10, 10),
              max_iter=100)

In [11]:
predictions = mlp.predict(X_test)

In [12]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions,digits=4))

[[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0 25  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  1 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0]
 [ 1  0  1  0  0  0 

In [13]:
print("w1 = ")
print(mlp.coefs_[0])
print("w2 = ")
print(mlp.coefs_[1])
print("w3 = ")
print(mlp.coefs_[2])

w1 = 
[[-0.37515116  0.80897433  0.44552488 -0.07952736  0.03049056 -0.23636811
  -0.10607661 -0.6238957  -0.83244413  0.59189994]
 [ 0.19922816  0.31065128  0.6744674  -0.52735848 -1.13737572  0.51809603
   0.18099973  1.33573367 -0.23733115 -0.17980733]
 [-1.02806287 -0.30971148 -0.47320345 -0.61742271  0.46604938 -0.37576205
   0.56671943  0.00469651 -1.04605428  0.79398758]
 [ 0.229448   -0.17264433  0.4866193   0.95588231  0.11998598 -0.91905378
   0.58918621  0.37716631  0.75637769  0.87525377]
 [ 0.41469731 -0.67009015  0.8299149   0.9040453  -0.28685564 -0.05875785
  -0.55286276  0.67305628 -0.50927371 -0.33183683]
 [-0.1212467  -0.12191671 -0.0763599   0.32260486 -0.31737897 -1.13671947
   0.59628965  0.70399528  0.0396199  -0.8407584 ]
 [-0.68768971 -0.11627961  0.8637123   0.21495464 -0.35767797  0.51965857
   0.48842677 -1.09171444 -0.34654211 -0.84334043]
 [ 0.66569856  1.01085166  0.09289385 -0.53954568 -0.5446148  -0.03640892
   0.68986172 -0.39223144  0.90989548  0.1762

In [14]:
print("bias1 = ")
print(mlp.intercepts_[0])
print("bias2 = ")
print(mlp.intercepts_[0])
print("bias3 = ")
print(mlp.intercepts_[0])

bias1 = 
[ 0.24434827  0.09233995 -0.29126215 -0.33606569 -0.09084994  0.36463111
  0.0552123   0.17560411  0.17177556  0.19237227]
bias2 = 
[ 0.24434827  0.09233995 -0.29126215 -0.33606569 -0.09084994  0.36463111
  0.0552123   0.17560411  0.17177556  0.19237227]
bias3 = 
[ 0.24434827  0.09233995 -0.29126215 -0.33606569 -0.09084994  0.36463111
  0.0552123   0.17560411  0.17177556  0.19237227]


In [15]:
predictions

array([29, 30, 14, 30, 22,  9, 11,  5, 14, 29,  6, 24,  9, 11, 22, 26,  9,
       10, 10, 12, 11, 15, 27,  3, 30, 14,  8,  8, 26, 20, 12, 17,  2, 25,
       19, 21, 21, 18,  7, 16,  1,  9, 25, 28, 22, 18,  7, 13, 22, 27, 19,
       22, 31, 20,  1,  5,  4, 24, 24,  2, 20, 22,  2, 13, 25, 21, 10, 25,
       13,  5, 27, 16,  5, 25, 25, 15, 15, 26, 22, 20,  8,  9, 26, 21, 28,
        7, 15, 13, 25, 10,  3, 24, 27, 21, 25, 31, 11, 16,  9,  2,  6,  6,
       24, 22,  3, 31,  5,  7, 11,  8, 18,  6, 14, 26, 19, 29,  6, 10,  3,
       21, 13,  5, 21, 23, 23, 21, 15,  3,  9, 27,  5, 27, 13, 17,  8,  1,
        2, 11,  8,  4, 22, 30, 18,  6,  2, 12,  6, 30,  3, 31, 20, 23,  5,
       17, 30, 25,  2, 15, 20, 25, 25, 13, 25,  7, 19, 21, 18, 30, 25, 26,
        6,  5,  4, 20, 28,  5, 12, 28, 16, 31,  1, 25, 26, 21,  4, 20,  6,
       16, 19,  2, 12, 17, 25, 18, 29,  9,  1, 21, 29, 16, 28, 17,  7, 22,
        5,  8, 28,  9, 26, 10, 22, 18, 25, 11,  9, 18,  7, 28, 30, 27,  5,
       29, 10,  2, 10,  3

In [16]:
nilai= np.array([0.3188,0.1244,0.0154,0.0217,0.0183,0,0.0105,0.003,0.0017])

In [22]:
nilai=nilai.reshape(1,9)

In [23]:
nilai.shape
print(nilai)

[[0.3188 0.1244 0.0154 0.0217 0.0183 0.     0.0105 0.003  0.0017]]


In [24]:
a=mlp.predict(nilai)

In [25]:
print(a)

[22]
